### ISSUE TITLE
T01: crear migraciones de la base de datos

### ISSUE THREAD

**Issue by Yngwiie** [lgsilvestre/StudentTimeLine_G3#1]
Se deben crear las migraciones de la base de datos, para poder crear la base de datos rápidamente utilizando php artisan migrate.

**Comment by Yngwiie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T06: Creación de migraciones de la base de datos](https://trello.com/c/Hw8QtnSd/25-t06-creaci%C3%B3n-de-migraciones-de-la-base-de-datos)

**Comment by javicabrera** [comment]
Se rellenan últimas tablas de migraciones con los atributos correspondientes. @IgnacioBurgos

**Comment by IgnacioBurgos** [comment]
Se crearon todas las migraciones:
2)Carrera
3)Estudiante
4)Carrera_Estudiante
5)Carrera_Usuario
6)Observacion
7)Usuario_Observacion_Estudiante

y además las tablas que se crearon al momento de la instalación de roles y permisos que con ello viene las tablas:

1) Usuarios
2)Roles
3)Permisos
4)Permisos_Roles.

y se rellenan todas las tablas con sus respectivos atributos.
