### ISSUE TITLE
T14: Creación controladores de los modelos

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#15]
Creación de controladores con métodos preliminares por laravel.

**Comment by javicabrera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T14: Crear controladores de los modelos](https://trello.com/c/q3OAqYuH/40-t14-crear-controladores-de-los-modelos)

**Comment by javicabrera** [comment]
Se crearon los controladores con los metodos por defecto de usuario, rol, estudiante, carrera, observacion y permiso.

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T20: Arreglar atributos en las migraciones, según el formato que ingresaran estudiantes](https://trello.com/c/z9Gow5n5/54-t20-arreglar-atributos-en-las-migraciones-seg%C3%BAn-el-formato-que-ingresaran-estudiantes)
