### ISSUE TITLE
T16: Implementar métodos principales del controlador de estudiantes.

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#19]
Realizar los métodos principales correspondientes al controlador de estudiantes.

**Comment by javicabrera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T16: Implementar métodos principales del controlador de estudiantes](https://trello.com/c/o2fw4J21/51-t16-implementar-m%C3%A9todos-principales-del-controlador-de-estudiantes)

**Comment by is4vo** [comment]
El método _edit()_ no se implementa ya que no se requiere editar la información de un estudiante.

**Comment by javicabrera** [comment]
Se implementaron los métodos de index, create, store, update y destroy. @is4vo
