### ISSUE TITLE
T02: Crear seeders(semillas) que tendra la base de datos por default.

### ISSUE THREAD

**Issue by Yngwiie** [lgsilvestre/StudentTimeLine_G3#2]
Los datos semillas son los datos que tendrá la base de datos por default, por lo que deben contener
los roles(profesor, administrador, secretaría de escuela) y los posibles permisos(agregar observación, eliminar observación, agregar carrera, etc.)

**Comment by is4vo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T07: crear seeders que tendrá la base de datos por default.](https://trello.com/c/PVn5Qep2/26-t07-crear-seeders-que-tendr%C3%A1-la-base-de-datos-por-default)

**Comment by is4vo** [comment]
Se crean seeders de las tablas de Roles, Usuarios y Carreras.
