### ISSUE TITLE
T17: Implementar métodos principales de controlador Usuario

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#24]
Se deben implementar los métodos principales pertenecientes al controlador Usuario.

**Comment by javicabrera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T17: Implementar métodos principales del controlador Usuario](https://trello.com/c/hOKW0gvc/52-t17-implementar-m%C3%A9todos-principales-del-controlador-usuario)

**Comment by javicabrera** [comment]
Se escribio la funcion de una busqueda en el modelo de usuario, para poder filtrarlos. @is4vo

**Comment by javicabrera** [comment]
Se realizaron los métodos del UserController index, store, create, edit, udpate @is4vo

**Comment by is4vo** [comment]
Falta revisión de update y dudas que aclarar sobre usuario administrador @Yngwiie

**Comment by is4vo** [comment]
@javicabrera se implementa SoftDelete en el controlador de usuario, modificando el modelo y las migraciones necesarias.
