### ISSUE TITLE
T26: Implementar nueva migracion para la tabla categoria, su modelo y sus seeds

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#34]
Se debe crear una nueva migracion para la tabla categoria, junto con su modelo y seed.

**Comment by javicabrera** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T26: implementar nueva migración para la tabla categoría, su modelo y sus seeds](https://trello.com/c/8IQBDxOA/61-t26-implementar-nueva-migraci%C3%B3n-para-la-tabla-categor%C3%ADa-su-modelo-y-sus-seeds)

**Comment by javicabrera** [comment]
Se implementa la migracion para la tabla categoria

**Comment by is4vo** [comment]
Se crea el seeder de categorías, las cuales son: Ayudantía, Práctica, Copia, Otro, En Observación - 1 por Tercera, En Observación - 1 por Segunda, Se Retira, Eliminado por Rendimiento, Titulado, Eliminado Art. 31 E, Eliminado Art. 31 B.

**Comment by javicabrera** [comment]
Se actualiza modelo y migracion de la observacion debido a la modificacion del atributo categoria.

**Comment by is4vo** [comment]
@Yngwiie @IgnacioBurgos Falta modificar controlador de observaciones para que funcione.

**Comment by javicabrera** [comment]
Migración de categoria realizada, junto a su modelo y seeders con @is4vo
