### ISSUE TITLE
T04: implementar validación de datos de inicio de sesión 

### ISSUE THREAD

**Issue by Yngwiie** [lgsilvestre/StudentTimeLine_G3#4]
Se deben validar los datos que serán enviados a través de una request desde la vista de inicio de sesión, quiere decir si los datos ingresados están registrados en la base de datos.

**Comment by is4vo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T09: implementar validación de datos de inicio de sesión[13]](https://trello.com/c/jd5a7Hl9/23-t09-implementar-validaci%C3%B3n-de-datos-de-inicio-de-sesi%C3%B3n13)

**Comment by Yngwiie** [comment]
Las validaciones del inicio de sesión vienen predeterminadas al instalar el proyecto de laravel con la opción --auth
