### ISSUE TITLE
T34: Crear seeders de los módulos de las carreras de la facultad de ingeniería

### ISSUE THREAD

**Issue by IgnacioBurgos** [lgsilvestre/StudentTimeLine_G3#41]
Se deben crear los seeders de las demás carreras de la facultad de Ingeniería
1) Ingeniería Civil Industrial
2) Ingeniería Civil Obras Civiles
3) Ingeniería Civil Minas
4) Ingeniería Civil en Mecatrónica
5) Ingeniería Civil Mecánica
6) Ingeniería Civil Eléctrica

**Comment by IgnacioBurgos** [comment]
se crean los seeders de los de 3 carreras de Ingeniería 
Industrial, Obras Civiles y Minas.

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T34: Crear seeders de los módulos de las carreras de la facultad de ingeniería](https://trello.com/c/Yxv9VHUO/71-t34-crear-seeders-de-los-m%C3%B3dulos-de-las-carreras-de-la-facultad-de-ingenier%C3%ADa)

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T34: Crear seeders de los módulos de las carreras de la facultad de ingeniería](https://trello.com/c/Yxv9VHUO/71-t34-crear-seeders-de-los-m%C3%B3dulos-de-las-carreras-de-la-facultad-de-ingenier%C3%ADa)

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T34: Crear seeders de los módulos de las carreras de la facultad de ingeniería](https://trello.com/c/Yxv9VHUO/71-t34-crear-seeders-de-los-m%C3%B3dulos-de-las-carreras-de-la-facultad-de-ingenier%C3%ADa)

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T34: Crear seeders de los módulos de las carreras de la facultad de ingeniería](https://trello.com/c/Yxv9VHUO/71-t34-crear-seeders-de-los-m%C3%B3dulos-de-las-carreras-de-la-facultad-de-ingenier%C3%ADa)

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T34: Crear seeders de los módulos de las carreras de la facultad de ingeniería](https://trello.com/c/Yxv9VHUO/71-t34-crear-seeders-de-los-m%C3%B3dulos-de-las-carreras-de-la-facultad-de-ingenier%C3%ADa)

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T34: Crear seeders de los módulos de las carreras de la facultad de ingeniería](https://trello.com/c/Yxv9VHUO/71-t34-crear-seeders-de-los-m%C3%B3dulos-de-las-carreras-de-la-facultad-de-ingenier%C3%ADa)

**Comment by javicabrera** [comment]
Se crea el seeder de todos los módulos de la carrera Ing Civil Mecatrónica

**Comment by javicabrera** [comment]
Se crearon los seedres de todos los modulos de la carrera Ing Civil Mecanica

**Comment by javicabrera** [comment]
Se crearon los seeders de todos los modulos de la carrera Ing Civil Eléctrica.

**Comment by javicabrera** [comment]
Por favor revisar el comentario de la línea 667 de los seeders de modulo @Yngwiie @IgnacioBurgos faltaria eso para cerrar la Issue
