### ISSUE TITLE
T37: Implementar vista perfil de usuario [5]

### ISSUE THREAD

**Issue by ArielVF** [lgsilvestre/StudentTimeLine_G3#44]
T37: Implementar vista perfil de usuario [5]

**Comment by ArielVF** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T37: Implementar vista perfil de usuario [5]](https://trello.com/c/whwFagTL/74-t37-implementar-vista-perfil-de-usuario-5)

**Comment by IgnacioBurgos** [comment]
@ArielVF Se crea la vista de perfil de usuario con el nombre, correo y una foto elegida por el usuario al momento de la creación de éste. Si no ingresa una foto, por defecto se le agregará una foto .
