### ISSUE TITLE
T38: Implementar el listar estudiantes de una carrera específica

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#45]

**Comment by is4vo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T38: Implementar el listar estudiantes de una carrera especifica. [5]](https://trello.com/c/PGxFwMwT/75-t38-implementar-el-listar-estudiantes-de-una-carrera-especifica-5)

**Comment by is4vo** [comment]
@javicabrera @Yngwiie Se implementa la vista del listado de estudiantes de una carrera

**Comment by ArielVF** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T40: agregar iconos en los placeholder de los formularios[3]](https://trello.com/c/uH6HkqiX/77-t40-agregar-iconos-en-los-placeholder-de-los-formularios3)
