### ISSUE TITLE
T49: Implementar vista de ver observaciones de un estudiante [20]

### ISSUE THREAD

**Issue by ArielVF** [lgsilvestre/StudentTimeLine_G3#59]
@javicabrera @Rubenrv95 Avance con vista de estudiante para agregar observaciones. Todavía no hay nada funcional.

**Comment by ArielVF** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T49: Implementar vista de ver observaciones de un estudiante [20]](https://trello.com/c/17GcrnV4/86-t49-implementar-vista-de-ver-observaciones-de-un-estudiante-20)

**Comment by javicabrera** [comment]
Se realizan los avances en agregar nueva observacion de un estudiante junto a @Rubenrv95 @ArielVF

**Comment by ArielVF** [comment]
@Rubenrv95 @ArielVF
Se vincula controlador con vista.
Funcionalidad para agregar observaciones ok.
Se ajusta vista y algunos detalles.
Falta editar observaciones y datos del estudiante.
