### ISSUE TITLE
T54: Implementar editar una observación añadida

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#64]
Se debe implementar la vista y funcionalidad de una observacion añadida.

**Comment by javicabrera** [comment]
Se agrega un boton a la tarjeta de la observacion y se crea el modal de editar observacion

**Comment by ArielVF** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T54: Implementar editar una observación añadida](https://trello.com/c/c2uFYYeI/91-t54-implementar-editar-una-observaci%C3%B3n-a%C3%B1adida)

**Comment by ArielVF** [comment]
Se añaden botones para editar y eliminar una observación.
Funcionalidad para eliminar una observación, lista.
Funcionalidad para editar una observación se encuentra en un 80%.

**Comment by ArielVF** [comment]
Editar observación, Ok.
Botones para editado y eliminación, Ok
