### ISSUE TITLE
T60: Arreglar el agregar estudiante de manera individual, muchos datos( posible solucion: wizard)

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#72]
Arreglar de manera visual como agregar un estudiante

**Comment by javicabrera** [comment]
[https://codepen.io/nickduskey/pen/WdZRKV](url) Posible Wizard

**Comment by Rubenrv95** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T60: Arreglar el agregar estudiante de manera individual, muchos datos( posible solucion: wizard)](https://trello.com/c/WeCN1Ueq/97-t60-arreglar-el-agregar-estudiante-de-manera-individual-muchos-datos-posible-solucion-wizard)

**Comment by javicabrera** [comment]
Se implemento la nueva vista de agregar estudiante en conjunto con @Rubenrv95, nos quedo pendiente hacer que sea funcional y revisar detalles dela barra de progreso y añadir un boton de volver atrás.

**Comment by javicabrera** [comment]
En conjunto a  @Rubenrv95 se implemento la funcionalidad a la nueva vista de agregar estudiante, además se hicieron modificaciones a la barra de progreso para que cuando se retroceda a la pestaña anterior, ésta igual lo haga.
