### ISSUE TITLE
T71: Implementar generar reporte de un estudiante

### ISSUE THREAD

**Issue by javicabrera** [lgsilvestre/StudentTimeLine_G3#79]

**Comment by is4vo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T71: Implementar Generar reporte de un solo estudiante](https://trello.com/c/j3fLYrAU/108-t71-implementar-generar-reporte-de-un-solo-estudiante)

**Comment by javicabrera** [comment]
El dia miercoles se implemento la interfaz gráfica para poder generar cualquier tipo de reporte con @is4vo

**Comment by javicabrera** [comment]
Se realiza la exportación de estudiante de forma individual según su rut, @is4vo por favor validar detalles

**Comment by is4vo** [comment]
@javicabrera se arreglan errores de backend, falta arreglar 1 error de guardado de datos.
