### ISSUE TITLE
T05: crear modelos de BD

### ISSUE THREAD

**Issue by Yngwiie** [lgsilvestre/StudentTimeLine_G3#8]
crear modelos y controladores

**Comment by IgnacioBurgos** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [T12: Crear modelos de la BD](https://trello.com/c/srlWypou/29-t12-crear-modelos-de-la-bd)

**Comment by Yngwiie** [comment]
Se crean los modelos de las tablas estudiante, carrera, observación , tabla intermedia observación_usuario_estudiante y tabla intermedia usuario_carrera
